
// Contract addresses - DO NOT EDIT THIS FILE MANUALLY
// This file is automatically generated during deployment

export const JUROR_STAKING_ADDRESS = '0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512';
export const TOKEN_ADDRESS = '0x5FbDB2315678afecb367f032d93F642f64180aa3';
