
// Contract addresses - DO NOT EDIT THIS FILE MANUALLY
// This file is automatically generated during deployment

export const JUROR_STAKING_ADDRESS = '0x7a2088a1bFc9d81c55368AE168C2C02570cB814F';
export const TOKEN_ADDRESS = '0x4A679253410272dd5232B3Ff7cF5dbB88f295319';
