// This file is automatically generated during deployment

export const JUROR_STAKING_ADDRESS = '0x322813Fd9A801c5507c9de605d63CEA4f2CE6c44';
export const TOKEN_ADDRESS = '0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9';
